### ISSUE TITLE
Capital tags don't work

### ISSUE THREAD

**Issue by MatrixSenpai** [LiveTL/Safari#1]
Capital tags seem to fail to parse only in safari

`[en]` works but `[EN]` doesn't

edit: can't spell

**Comment by MatrixSenpai** [comment]
seems to only be affecting safari

**Comment by Candygoblen123** [comment]
"it works on my machine"
<img width="1525" alt="Screen Shot 2021-01-08 at 10 54 13 AM" src="https://user-images.githubusercontent.com/28193374/104035288-f65ef400-519f-11eb-929d-3f22bda48af0.png">

**Comment by MatrixSenpai** [comment]
Not sure what was going on, but it seems to be working now. maybe something misconfigured
